SELECT PRODUCT_CODE, PRICE*SALES_AMOUNT AS SALES
FROM PRODUCT JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID) AS S
ON PRODUCT.PRODUCT_ID=S.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE;