WITH T AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT RI.FOOD_TYPE
     , RI.REST_ID
     , RI.REST_NAME
     , T.FAVORITES
FROM REST_INFO RI
     JOIN T
     ON RI.FOOD_TYPE = T.FOOD_TYPE
        AND RI.FAVORITES = T.FAVORITES
ORDER BY FOOD_TYPE DESC
;
     