SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, O.NAME
FROM (
        SELECT *
        FROM ANIMAL_INS
        WHERE SEX_UPON_INTAKE LIKE 'Intact%'
    ) I JOIN
    ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.SEX_UPON_OUTCOME LIKE 'Spayed%' 
    OR O.SEX_UPON_OUTCOME LIKE 'Neutered%'
ORDER BY I.ANIMAL_ID
;