SELECT P.YEAR
     , P.MONTH
     , P.PURCHASED_USERS
     , ROUND(P.PURCHASED_USERS / (
        SELECT COUNT(*)
        FROM USER_INFO
        WHERE YEAR(JOINED) = 2021
     ),1) PUCHASED_RATIO
FROM (
        SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT U.USER_ID) PURCHASED_USERS
        FROM USER_INFO U JOIN
                ONLINE_SALE O ON
                U.USER_ID = O.USER_ID AND YEAR(JOINED) = 2021
        GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
) P
ORDER BY YEAR, MONTH
;