SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FP 
    JOIN
        (
            SELECT *
            FROM FOOD_ORDER
            WHERE YEAR(PRODUCE_DATE) = "2022" AND MONTH(PRODUCE_DATE) = "05"
        ) FO
    ON FP.PRODUCT_ID = FO.PRODUCT_ID
GROUP BY FP.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID
;