WITH A AS (
    SELECT APNT_YMD, APNT_NO, PT_NO, MCDP_CD, MDDR_ID
    FROM APPOINTMENT
    WHERE DATE(APNT_YMD) = '2022-04-13'
          AND MCDP_CD = 'CS'
          AND APNT_CNCL_YN = 'N'
)


SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM A
JOIN PATIENT P ON P.PT_NO = A.PT_NO
JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
ORDER BY APNT_YMD
;