WITH FE_T AS (
    SELECT *
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),

FE_T_D AS (
    SELECT *
    FROM FE_T
    JOIN DEVELOPERS
    ON (FE_T.CODE & DEVELOPERS.SKILL_CODE) != 0
)

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM FE_T_D
ORDER BY ID
;