WITH R AS (
    SELECT MEMBER_ID
         , RANK() OVER (ORDER BY COUNT(*) DESC) AS RANKING
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)

SELECT M.MEMBER_NAME
     , RR.REVIEW_TEXT
     , DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN REST_REVIEW RR
ON M.MEMBER_ID = RR.MEMBER_ID
WHERE M.MEMBER_ID IN (
        SELECT MEMBER_ID
        FROM R
        WHERE RANKING = 1
    )
ORDER BY REVIEW_DATE, REVIEW_TEXT
;