WITH MAX_YEARLY AS (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MAX(SIZE_OF_COLONY) MAX_COLONY, ID
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
),
ECOLI AS (
    SELECT ID, SIZE_OF_COLONY, YEAR(DIFFERENTIATION_DATE) YEAR
    FROM ECOLI_DATA
)

SELECT Y.YEAR, Y.MAX_COLONY - E.SIZE_OF_COLONY YEAR_DEV, E.ID
FROM MAX_YEARLY Y
     JOIN ECOLI E
     ON Y.YEAR = E.YEAR
ORDER BY YEAR, YEAR_DEV
;