name: Organize Code by Language

# GitHub Actions를 push 이벤트에서 실행
on:
  push:
    branches:
      - main  # 'main' 브랜치에 푸시될 때마다 실행

jobs:
  organize_files:
    runs-on: ubuntu-latest  # GitHub Actions가 실행될 환경

    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Python 파일을 'python' 폴더로 이동
      - name: Move Python files
        run: |
          mkdir -p python  # 'python' 폴더가 없으면 생성
          mv *.py python/  # .py 파일들을 'python' 폴더로 이동

      # 3. JavaScript 파일을 'javascript' 폴더로 이동
      - name: Move JavaScript files
        run: |
          mkdir -p javascript  # 'javascript' 폴더가 없으면 생성
          mv *.js javascript/  # .js 파일들을 'javascript' 폴더로 이동

      # 4. 변경사항을 Git에 커밋하고 푸시
      - name: Commit changes
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add .
          git commit -m "Organize files by language"
          git push
